name: CI Pipeline (Model Training)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Dependencies (PERBAIKAN DISINI)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Masuk ke folder dulu baru install
        cd Membangun_model  
        pip install -r requirements.txt

    # 4. Run Training (PERBAIKAN DISINI)
    - name: Run Model Re-training
      run: |
        # Masuk ke folder dulu baru jalankan script
        cd Membangun_model
        python modelling_tuning.py
