name: CI/CD Pipeline to Docker Hub

# Workflow jalan saat ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Login ke Docker Hub (Menggunakan Kunci Rahasia)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build Image & Push ke Docker Hub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        # PENTING: Lokasi Dockerfile ada di dalam folder MLProject
        context: ./MLProject
        push: true
        # GANTI BAGIAN INI: username/repo:tag
        tags: benedictusaryantio/ml-project-submission:latest