name: CI Pipeline (Model Training)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Library (Kita install manual karena requirements.txt tidak ada)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install library penting yang biasa dipakai
        pip install pandas scikit-learn mlflow matplotlib joblib numpy

    # 4. Run Training (Dengan nama folder & file yang BENAR)
    - name: Run Model Re-training
      run: |
        # Masuk ke folder MLProject
        cd MLProject
        # Jalankan script modelling.py
        python modelling.py
